// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynovnfiyctsyffcblqpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlub3ZuZml5Y3RzeWZmY2JscXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTA0MTQsImV4cCI6MjA2MjQ2NjQxNH0.90E2RAWuh9TZVVQeE14SR3okdta6kXC88mEGoPhurzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);